### ISSUE TITLE
percels issue

### ISSUE THREAD

**Issue by berzinastella** [philippemiron/xlcs#5]
Hi,
This package of code looks exactly like what I need, so thanks !! 
But I'm trying to run the ex1-lavd notebook and when trying to import functions from the lagrangian_tools.py there is an error

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 8
      4 import sys
      6 sys.path.append("../xlcs/")
----> 8 import lagrangian_tools as lt
      9 import grid_calc
     10 from custommap import *

File [~/xlcs/examples/../xlcs/lagrangian_tools.py:14](https://jupyterhub.dkrz.de/user/b382618/levante-spawner-preset/lab/tree/home/b/b382618/xlcs/examples/~/xlcs/xlcs/lagrangian_tools.py#line=13)
     12 import xgcm
     13 import gsw
---> 14 from parcels import FieldSet, ParticleSet, JITParticle, AdvectionRK4, ErrorCode
     15 # from parcels import FieldSet, ParticleSet, JITParticle, AdvectionRK4
     17 from typing import Optional

ImportError: cannot import name 'ErrorCode' from 'parcels' ([/home/b/b382618/.conda/envs/parcels2/lib/python3.11/site-packages/parcels/__init__.py]
```

Is it because of the wrong parcels version? I have the latest parcels 3.0.4

Thanks!!
Best,
Stella

**Comment by berzinastella** [comment]
Hi again,
nevermind, it is just a naming issue in parcels.

ErrorCode is now called StatusCode, so that solves the issue.

Additionally, with the most recent parcels version you need to remove the recovery statement in  pset.execute() in the lagrangian_tools.py.

Anyway, thanks !!
Stella

**Comment by philippemiron** [comment]
Thanks for reporting it. I haven't used the code in a while, but I will fix it.
